markdown: redcarpet
pygments: null
permalink: /:title
encoding: utf-8

url: http://pankajmalhotra.com
baseurl:

twitter_username: bitgeekypankaj


github: bitgeeky
twitter: bitgeekypankaj
email: devpankaj1994@gmail.com
linkedin: bitgeekypankaj
stackoverflow: users/2437097/bitgeeky

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
