markdown: redcarpet
highlighter: null
permalink: /:title
encoding: utf-8

url: http://pankajmalhotra.com
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
